# Generated by Django 5.1.6 on 2025-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='map',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestate',
            name='turn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
